### ISSUE TITLE
new lesson: Introduction to Arrays

### ISSUE THREAD

**Issue by Utkarsh1504** [Utkarsh1504/DSA-Java#1]
### ⭐ Request Type

Add proper documentation for the lesson `Introduction to Arrays` in the [file](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/arrays.md)

### 💻 Location

This lesson is present under the
Section: `4`
Lesson: `A`
File-Name: `arrays.md`

### ❌ Additional Info

You can take the help of other markdown files in the `/lesson` [directory](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/operators.md)

Introduction to Arrays must consist of at least the following topic:

1. why arrays + what is an array?
2. syntax + indexing + internal working.
3. basic example for the array(program code).
4. memory allocation
5. input an array + output an array.

**Comment by daniellekush** [comment]
Hey, I'm new to contributing but I'd like to take this on if possible.

**Comment by Utkarsh1504** [comment]
@daniellekush absolutely go-ahead.

**Comment by mriceflame** [comment]
Can i start working on it now? and merge my PR during Hacktoberfest?

**Comment by Utkarsh1504** [comment]
@mriceflame sure.

**Comment by paltannistha** [comment]
I want to work on this issue.

**Comment by Utkarsh1504** [comment]
@paltannistha I think people already working on this issue, but don't worry I will raise a lot more issues in the upcoming days.

**Comment by paltannistha** [comment]
@Utkarsh1504 okay thank you.

**Comment by Ayan-thecodeking** [comment]
pls assign me i want to work on this issue

**Comment by shoebxsiddiqui** [comment]
\assign

**Comment by rushikeshadhav** [comment]
Can I contribute?
Please assign this to me.
Thank you

**Comment by Utkarsh1504** [comment]
@rushikeshadhav ok you can start working on it.
Please take reference from https://www.youtube.com/watch?v=n60Dn0UsbEk video, and make document according to that.
Thank you!

**Comment by aastha01chauhan** [comment]
hey, I want to contribute here, please assign this issue to me

**Comment by Utkarsh1504** [comment]
@aastha01chauhan this issue is already assigned by someone. you can work on other issues I'll raise more issues.

**Comment by Mitz190** [comment]
Can I contribute?
Please assign this to me.
Thank you

**Comment by utkarshgupta611** [comment]
Can I contribute?
Please assign this to me.
Thank you

**Comment by shoebxsiddiqui** [comment]
I will work on this
