### ISSUE TITLE
improve: Standard Practice Questions on Recursion 

### ISSUE THREAD

**Issue by sujoy-coder** [Utkarsh1504/DSA-Java#104]
### ⭐ Summary

Hi @Utkarsh1504 
I would like to work on **Standard Practice Questions** on **Recursion** section. Here I will take popular question on recursion and explain that with codes.
Please assign it to me.
_Thanks_

### 💻 Location

title: Standard Practice Questions
section: Recursion
order: 8G
filename: [recursion-practise.md](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/recursion-practise.md)

### ❌ Additional Info

_#hacktoberfest2021_

**Comment by Utkarsh1504** [comment]
@sujoy-coder absolutely go ahead. Just share the question you want to add.
