### ISSUE TITLE
Can you create one for DSA in cpp?

### ISSUE THREAD

**Issue by mriceflame** [Utkarsh1504/DSA-Java#13]
### Other

This will help alot of beginners to contribute who study DSA in cpp

**Comment by Utkarsh1504** [comment]
ok I will create one more on C++

**Comment by ananya0504** [comment]
I can contribute to the one in C++

**Comment by Utkarsh1504** [comment]
@ananya0504 I haven't created a website for c++ yet, 
you can contribute in java if you want
