### ISSUE TITLE
new lesson: Binary Search Tree 

### ISSUE THREAD

**Issue by Buddhad** [Utkarsh1504/DSA-Java#15]
### ⭐ Request Type

Add in-depth documentation for binary-search-tree algorithm [here](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/intro-bst.md).

### 💻 Location

This lesson is present under the
Section: `16`
Lesson: `A`
Location Order: `16A`
File-Name: `intro-bst.md`

### ❌ Additional Info

You can take the help of other markdown files in the /lesson [directory](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/operators.md)

This lesson must consist of at least the following topic:

introduction to the `binary search tree algorithm`
code for binary search Tree
examples based on binary search Tree
complexity analysis(in brief)

**Comment by roshaan005** [comment]
Can I work on this issue?

**Comment by Utkarsh1504** [comment]
Thank you for your interest in contributing to our Repo:
- this issue is already taken by @Buddhad.
- you can start working on the other issues.
- And don't worry I'll create more issues by the time so anyone can work on them.
