### ISSUE TITLE
Can you create DSA in Java

### ISSUE THREAD

**Issue by DurveshKumarPal** [Utkarsh1504/DSA-Java#17]
### ⭐ Request Type

Add some DSA problems in java.

This will help alot of beginners to contribute who study DSA in Java

### 💻 Location

-

### ❌ Additional Info

beginners to contribute who study DSA in Java

**Comment by Utkarsh1504** [comment]
@DurveshKumarPal This is already DSA in Java. 
We will add questions in Assignment Section which is the last section

**Comment by DurveshKumarPal** [comment]
@Utkarsh1504 Oh, I got it section

**Comment by DurveshKumarPal** [comment]
@Utkarsh1504 in Java DSA lesson has no code.

**Comment by Utkarsh1504** [comment]
@DurveshKumarPal yes, there is a lot of work is to be done, you can contribute to this repo that will help us a lot and you too

**Comment by DurveshKumarPal** [comment]
sure but add code only??

**Comment by Utkarsh1504** [comment]
@DurveshKumarPal  no, you can take reference from this [markdown](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/loops.md) and in the same fashion, you have to write for others.
