### ISSUE TITLE
new lesson: Insertion Sort

### ISSUE THREAD

**Issue by Utkarsh1504** [Utkarsh1504/DSA-Java#23]
### ⭐ Request Type

Add in-depth documentation on the sorting algorithm Insertion Sort.
The markdown file is located [here](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/insertion.md).
## Lesson Content
The lesson must contain at least these are the topics:

1. Introduction to Insertion Sort
2. Complete explanation on Insertion sort
3. Complexity Analysis of Insertion Sort
4. Worst-Case + Best Case
5. Code for Insertion Sort
6. Explanation of Code Example

### 💻 Location

This lesson is present under the
Section: `5`
Lesson: `E`
Location Order: `5E`
File-Name: [`insertion.md`](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/insertion.md)

### ❌ Additional Info

You can take the help of other markdown files in the [`/lesson`](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/loops.md) directory so that you get the idea of in which fashion you should write.

If you don't know how to do markdown, don't worry it is quite easy, just follow this docs-https://guides.github.com/features/mastering-markdown/

If your concepts are not that good follow this Insertion sort video of @kunal-kushwaha (https://www.youtube.com/watch?v=By_5-RRqVeE)

**Comment by Abhijit25Mishra** [comment]
hey i can do this. I am a 3 star at codechef and have a lot of experience in cp.

**Comment by Utkarsh1504** [comment]
@Abhijit25Mishra sure, but please write those notes which are taught by @kunal-kushwaha in his tutorials.
you can add your own notes as a markdown too but the first preference goes to DSA-Bootcamp-Java notes.
