### ISSUE TITLE
new lesson: Cycle Sort

### ISSUE THREAD

**Issue by Utkarsh1504** [Utkarsh1504/DSA-Java#24]
### ⭐ Request Type

Add in-depth documentation on the sorting algorithm Cycle Sort.
you need to create a markdown file for this.

### Lesson Content
The lesson must contain at least these are the topics:

1. Introduction to Cycle Sort
2. Complete explanation on Cycle Sort
3. Complexity Analysis of Cycle Sort
4. Worst-Case + Best Case
5. Code for Cycle Sort
6. Explanation of Code Example

### 💻 Location

This lesson should be present under the
Section: `5`
Lesson: `F`
Location Order: `5E`
File-Name: `cyclesort.md`

### ❌ Additional Info

You can take the help of other markdown files in the [/lesson](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/loops.md) directory so that you get the idea of in which fashion you should write.

If you don't know how to do markdown, don't worry it is quite easy, just follow this docs-https://guides.github.com/features/mastering-markdown/

If your concepts are not that good follow this Cycle sort video of @kunal-kushwaha (https://www.youtube.com/watch?v=JfinxytTYFQ)

**Comment by aniket-24** [comment]
Please assign me this issue!

**Comment by RahulSoni0** [comment]
Can i work on this issue ?

**Comment by satyamgupta1495** [comment]
I'd love to work on this issue! could you please assign me this?
