### ISSUE TITLE
new lesson: Move All Zeros to End of an Array

### ISSUE THREAD

**Issue by aniketartani** [Utkarsh1504/DSA-Java#31]
### ⭐ Request Type

You have been given a random integer array of size N. You have been required to push all the zeros that are present in the array to the end of it such that the relative order of the non-zero elements should be maintained.

### 💻 Location

This lesson is present under the
Section: 5
Lesson: E
Location Order: 5E
File-Name: Move.md

### ❌ Additional Info

This lesson must consist of at least the following topic:
Approach
Program
Time Complexity

**Comment by aniketartani** [comment]
@Utkarsh1504  can you please assign me this and add tags in this issue.

**Comment by ananya0504** [comment]
Hi, I would like to contribute to this issue!

**Comment by Utkarsh1504** [comment]
@aniketartani This is a standard question, not a concept, so, if you want to contribute this question and its approach feel free to create a file for all the standard questions related to searching  and sorting names as `practise-question.md` and then do your contribution
make sure to add this file to its correct location.
Thank you!

**Comment by Utkarsh1504** [comment]
@ananya0504 I'll raise more issues you can work on that,
till then keep your eyes on the issues section, Thank you!

**Comment by aniketartani** [comment]
@Utkarsh1504 Ok i will add all the questions regarding searching and sorting. Will it be considered under Hackoctober?

**Comment by aniketartani** [comment]
I need to add only questions , right?

**Comment by Utkarsh1504** [comment]
This lesson must consist of at least the following topic:
Approach
Program
program explanation
Time Complexity 
all these thing which you have mention

**Comment by aniketartani** [comment]
Approx how many programs should be there?

**Comment by Utkarsh1504** [comment]
As your wish, you can add one-two or many. All will be counted as meaning contribution

**Comment by sidsrivastavasks** [comment]
Hey, Assign me this task... I can solve it with proper explanation and clean code. I can solve this problem using all four languages - C, CPP, Java, and Python
