### ISSUE TITLE
Image in dataTypes.md is broken

### ISSUE THREAD

**Issue by tanishagupta1** [Utkarsh1504/DSA-Java#34]
### Other

![Screenshot (2665)](https://user-images.githubusercontent.com/73746588/135586219-ad6e92cb-525f-4967-ae58-808d611eb814.png)
The image just above the buttons is broken

### Additional information

It would be great if you could please assign this issue to me under hacktoberfest if find relevant

**Comment by Utkarsh1504** [comment]
@tanishagupta1 actually there is no image for in the /lesson/images folder if you wanted to contribute you can add image for datatypes in java.
make sure that the image is copyright free

**Comment by tanishagupta1** [comment]
Yeah sure, I'll add the image, is there any specification for the image?

**Comment by Utkarsh1504** [comment]
you can add whatever image looks good to you but it should be like this:
https://media.geeksforgeeks.org/wp-content/cdn-uploads/20191105111644/Data-types-in-Java.jpg

Don't use this exact image instead use a copyright-free image.  Thank you
