### ISSUE TITLE
improve: Operators in Java

### ISSUE THREAD

**Issue by Utkarsh1504** [Utkarsh1504/DSA-Java#4]
### ⭐ Summary

1. table in the 'increment and decrement operator' topic needs improvement.
2. all the code examples should be converted into java from c++.

### 💻 Location

Section: `3`
Lesson: `B`
Location Order: `3B`
File Name: `operator.md`

### ❌ Additional Info

[here](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/operators.md) you can start your contribution

**Comment by Vivek-Prajapatii** [comment]
Hii @Utkarsh1504, i'm interested in this and i'm new to open source can you please brief me about the issue

**Comment by Ayan-thecodeking** [comment]
can i work on this issue

**Comment by Utkarsh1504** [comment]
yes, you can.

**Comment by Ayan-thecodeking** [comment]
> yes, you can.

Thnx I'll make a pr ASAP

**Comment by DurveshKumarPal** [comment]
@Utkarsh1504 can you assign me this task i already complete half of the task

**Comment by tanishagupta1** [comment]
Hey @Utkarsh1504 , Since the issue which I raised earlier is not resolved with the linked PR can you assign me this issue to change the code

**Comment by Utkarsh1504** [comment]
@tanishagupta1 ok sure you can work on this
