### ISSUE TITLE
new lesson: Boyer-Moore Majority Voting Algorithm

### ISSUE THREAD

**Issue by Kajal13081** [Utkarsh1504/DSA-Java#43]
### ⭐ Request Type
Add the documentation for the lesson Boyer-Moore Majority Voting Algorithm.
Start your contribution from this [file](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/bmmv-algorithm.md)
I would like to make a document on the following algorithm. 
1. Boyer-Moore Majority Voting Algorithm

### 💻 Location
This lesson should be at:
Section: `4`
Lesson: `D`
Order: `4D`
File-name: [bmmv-algorithm](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/bmmv-algorithm.md)

### ❌ Additional Info

This lesson must consist of at least of the following things:
1. Introduction
2. Working
3. Implementation
4. Code example + explanation
5. Complexity analysis

**Comment by Kajal13081** [comment]
@Utkarsh1504 can I proceed with this issue?

**Comment by Kajal13081** [comment]
You have changed the topic of issue so do I have to work on only the last algorithm @Utkarsh1504 ?

**Comment by Utkarsh1504** [comment]
@Kajal13081 No you can work on all three I'll raise for that

**Comment by Utkarsh1504** [comment]
I have updated the issue and created the file also you can start writing your content in that, Thank you!

**Comment by Kajal13081** [comment]
sure
