### ISSUE TITLE
Operators in java(Explanatory code should be in java)

### ISSUE THREAD

**Issue by tanishagupta1** [Utkarsh1504/DSA-Java#47]
### ⭐ Summary

![Screenshot (2673)](https://user-images.githubusercontent.com/73746588/135706563-c6005a2b-6ddd-4ab1-b55f-7d517a110910.png)
The Explanatory code is in C++ in operators in java lesson, it should be rectified to a java example.

### 💻 Location

operators.md

**Comment by tanishagupta1** [comment]
I would like to work on this issue, if possible.

**Comment by rushikeshadhav** [comment]
Can I contribute?
Please assign this to me.
Thank you

**Comment by Utkarsh1504** [comment]
@tanishagupta1 Initially I was planning to make this website for C++ and then changed my mind to Java. That's why It is in C++.
An Issue for this is already created and also assigned to someone, if he does not work on this, I will assign that to you. Thank you!

**Comment by tanishagupta1** [comment]
ok sure thank you

**Comment by Utkarsh1504** [comment]
yes, sure!
