### ISSUE TITLE
new lesson: Jumps Statements

### ISSUE THREAD

**Issue by Utkarsh1504** [Utkarsh1504/DSA-Java#5]
### ⭐ Request Type

Add remaining documentation for the lesson `Jumps Statements` in the [file](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/jumps.md)

### 💻 Location

This lesson is present under the
Section: `3`
Lesson: `E`
Location Order: `3E`
File-Name: `jumps.md`

### ❌ Additional Info

[here](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/operators.md) you can take the help of other markdown files to have an idea in which format you should write.
This lesson must consist of at least the following topic:
1. break + code examples + explanation
2. continue + code examples + explanation
3. break vs continue
4. break vs continue vs return

**Comment by Ayushi7456** [comment]
I would like to work on this.

**Comment by Utkarsh1504** [comment]
@Ayushi7456 sure, go ahead.
make sure to read the contribution guidelines

**Comment by Subhadiptech** [comment]
I will love to work on this issue!

**Comment by Utkarsh1504** [comment]
@Subhadiptech you can work on other issues, I'll raise them later till then the fork and star the repo, and please the read contribution guidelines. Thank you!

**Comment by Subhadiptech** [comment]
Ok. Thats fine
