### ISSUE TITLE
Typo error in README.md

### ISSUE THREAD

**Issue by ananya0504** [Utkarsh1504/DSA-Java#55]
### Other

Line No. 88 of README.md
Request to change "git add -a" -> "git add ."

**Comment by Utkarsh1504** [comment]
oops, 
- there should be `git add -A` also 
- `git add .` this will work too.

Can you fix it? please make a PR I'll merge.
Thank you for pointing out the typo

**Comment by ananya0504** [comment]
Thanks, will this be accepted for HacktoberFest?

**Comment by Utkarsh1504** [comment]
No, unfortunately, type errors will not be considered for hacktoberfest, but still a helpful contribution
