### ISSUE TITLE
improve: <Java Development Setup>

### ISSUE THREAD

**Issue by KhafiaAyyub** [Utkarsh1504/DSA-Java#57]
### ⭐ Summary

1.More Explanation for Java Setup .
2.Reorganize the md file

### 💻 Location

Section: `Basics`
Lesson: `3`
Order: `2B`
File name: `java-setup.md`

**Comment by KhafiaAyyub** [comment]
can i work on this issue?

**Comment by Utkarsh1504** [comment]
@KhafiaAyyub please describe in brief what are the things you want to add in this lesson

**Comment by KhafiaAyyub** [comment]
> @KhafiaAyyub please describe in brief what are the things you want to add in this lesson

I would like to add setup for JAVA in different Operating System.

**Comment by Utkarsh1504** [comment]
ok sure make a PR if PR seems good to me then I'll add the hacktoberfest label.

**Comment by KhafiaAyyub** [comment]
> ok sure make a PR if PR seems good to me then I'll add the hacktoberfest label.

Okay, Thank you!
