### ISSUE TITLE
 suggested improvement Readme.md

### ISSUE THREAD

**Issue by tanishagupta1** [Utkarsh1504/DSA-Java#61]
### ⭐ Summary

The instructions require the local repository to set upstream as well for updated changes, which is currently missing the docs
![Screenshot (2675)](https://user-images.githubusercontent.com/73746588/135742142-3dbc271e-e35c-4fc3-87f7-c24f1efaf283.png)

### 💻 Location

readme.md

**Comment by Utkarsh1504** [comment]
Yes please improve the readme, thank you for raising this issue.
