### ISSUE TITLE
improve:  Space Complexity

### ISSUE THREAD

**Issue by Utkarsh1504** [Utkarsh1504/DSA-Java#63]
### ⭐ Summary

Please improve the documentation for the lesson space complexity, try to make to better.

If anyone wants to do it, I'll assign him.

### 💻 Location

section: 7
lesson: C
order: 7C
filename: [space-complexity.md](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/space-complexity.md)

### ❌ Additional Info

You can take the help of other markdown files in the [/lesson](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/loops.md) directory so that you get the idea of in which fashion you should write.

If you don't know how to do markdown, don't worry it is quite easy, just follow this docs-https://guides.github.com/features/mastering-markdown/

If your concepts are not that good follow this space and time complexity video of @kunal-kushwaha (https://www.youtube.com/watch?v=mV3wrLBbuuE)

**Comment by ananya0504** [comment]
Would love to contribute to this!
