### ISSUE TITLE
new lesson: ArrayList In Java

### ISSUE THREAD

**Issue by Utkarsh1504** [Utkarsh1504/DSA-Java#7]
### ⭐ Request Type

Add details documentation/content for the lesson `ArrayList In Java`.
you can start your contribution from [here](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/arraylist.md)

### 💻 Location

This lesson is present under the
Section: `4`
Lesson: `B`
Location Order: `4B`
File-Name: `arraylist.md`

### ❌ Additional Info

You can take the help of other markdown files in the /lesson [directory](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/operators.md)

This lesson must consist of at least the following topic:
1. Introduction
2. Syntax+Internal Working
3. code examples based on arraylist

**Comment by Ayushi7456** [comment]
I would like to work on this.

**Comment by Utkarsh1504** [comment]
@Ayushi7456 sure.

**Comment by preeti-14-7** [comment]
Can I work on this issue ?

**Comment by Utkarsh1504** [comment]
@preeti-14-7 I'll raise more issues, you can work on those.

**Comment by Utkarsh1504** [comment]
@preeti-14-7 I have assigned this issue to you, starting working on it, Thanks

**Comment by preeti-14-7** [comment]
> @preeti-14-7 I have assigned this issue to you, starting working on it, Thanks

okay sure!!

**Comment by preeti-14-7** [comment]
Can i add the info direct in website ?? i mean editing html file

**Comment by Utkarsh1504** [comment]
@preeti-14-7 no you have to do it in form of markdown, if you don't how to do markdown and markdown will be automatically converted into the HTML.
 - follow this resource - https://guides.github.com/features/mastering-markdown/ 
 - And in this file https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/arraylist.md you have to write about the Arraylist in Java
 - 
I hope you get this, you if still have any doubt feel free to ask, I'll guide you.

**Comment by preeti-14-7** [comment]
Can you add hacktoberfest tag in this issue. So that it will be counted in the event too.
