### ISSUE TITLE
improve: the explanations of the logical operators AND and OR: && vs. & and || vs. |

### ISSUE THREAD

**Issue by Guannan-Shen** [Utkarsh1504/DSA-Java#8]
### ⭐ Summary

Descriptions of &&(AND) and || (OR) might be misleading and less accurate:

```markdown
- `&&`: AND used to perform logical AND operation. It gives true if both the operands have true value.
- `||`: OR used to perform logical OR operation. It gives true if either of the operands have true value.
```

For instance, || gives true if the 1st operand has a  true value, and it will not try to evaluate the 2nd operand.
It might be helpful to mention **&** and **|** first, and then present a comparison between **&** and **&&**, as well as **|** and **||**.

### 💻 Location

See following markdown files:

https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/operators.md?plain=1#L73

https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/operators.md?plain=1#L74

**Comment by Utkarsh1504** [comment]
@Guannan-Shen thanks for raising the issue

**Comment by roshaan005** [comment]
I have a good grip on the AND and OR operators , if this issue is open , I'd love to contribute

**Comment by Utkarsh1504** [comment]
@roshaan005 sure, please do it.

**Comment by roshaan005** [comment]
on it!

**Comment by Utkarsh1504** [comment]
yes
