### ISSUE TITLE
new lesson: Number Theory Part-C (part-1)

### ISSUE THREAD

**Issue by Utkarsh1504** [Utkarsh1504/DSA-Java#80]
### ⭐ Request Type

Add in-depth documentation for the lesson Number Theory Part-C.
you can start your contribution from this [file](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/num-three.md)

## Lesson Content
The lesson must contain at least these are the topics:
1. Bitwise + DP
2. Extended Euclidean algorithm
3. Modulo Multiplicative Inverse
4. Linear Diophantine Equations
5. Matrix Exponentiation
6. Combinatorics

### 💻 Location

location of file is at:
section: 10
lesson: E
order: 10E
filename: [num-three.md](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/num-three.md)

### ❌ Additional Info

You can take the help of other markdown files in the [/lesson](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/loops.md) directory so that you get the idea of in which fashion you should write.

If you don't know how to do markdown, don't worry it is quite easy, just follow this docs-https://guides.github.com/features/mastering-markdown/

**Comment by priithaa** [comment]
Hi, @Utkarsh1504 I would like to contribute to this issue.

**Comment by Utkarsh1504** [comment]
@priithaa OK, Sure! This lesson will be quite lengthy you have to write a lot, don't burn out, take your time, and make your contribution. :octocat:  If you have any doubts regarding this you can ask in the discussion forum

**Comment by priithaa** [comment]
Yes, I will keep in mind, thank you!!

**Comment by Singhriddhi075** [comment]
Hello @Utkarsh1504 may I contribute on few topics because I think it's quite lengthy for one person?

**Comment by Utkarsh1504** [comment]
@Singhriddhi075 yes I am dividing this issue into two parts by doing the syllabus half and half, because this may be very long for both of you. You can drop a comment there and I will assign you part-2 of this issue.

**Comment by priithaa** [comment]
Yes @Utkarsh1504 this works
