### ISSUE TITLE
Precedence in operators.md

### ISSUE THREAD

**Issue by tanishagupta1** [Utkarsh1504/DSA-Java#87]
### ⭐ Summary

![Screenshot (2679)](https://user-images.githubusercontent.com/73746588/136147910-1b75ea44-12b1-42f5-b5ff-6cb6b9d58129.png)
Image or table of precedence is absent in operators.md

### 💻 Location

lessons/operators.md

**Comment by Utkarsh1504** [comment]
please add the precedence table or image which is convenient for you, and also give some examples of how to use the operator precedence. Thank you for raising this issue!

**Comment by tanishagupta1** [comment]
Sure I'll just raise a PR for this soon
