### ISSUE TITLE
improve: Printing Patterns

### ISSUE THREAD

**Issue by sujoy-coder** [Utkarsh1504/DSA-Java#89]
### ⭐ Summary

Hello @Utkarsh1504 
Here I would like to add a pattern printing concept with explanation + codes.
I love to contribute here, assign me.
_Thanks_

### 💻 Location

title: Printing Patterns
section: Arrays
order: 4C
filename: [print-patterns.md](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/print-patterns.md)

**Comment by shoebxsiddiqui** [comment]
assign
