### ISSUE TITLE
improve: Input/Output & Conditionals

### ISSUE THREAD

**Issue by Utkarsh1504** [Utkarsh1504/DSA-Java#9]
### ⭐ Summary
1. switch statement needs program explanation

### 💻 Location

Section: `3`
Lesson: `C`
Location Order: `3C`
File Name: `io-conditionals.md`

### ❌ Additional Info

[here](https://github.com/Utkarsh1504/DSA-Java/blob/main/lessons/io-conditionals.md) you can start your contribution

**Comment by DurveshKumarPal** [comment]
Hey, can I improve explanation in C++ to java

**Comment by Utkarsh1504** [comment]
@DurveshKumarPal absolutely yes.

**Comment by DurveshKumarPal** [comment]
#18

**Comment by ananya0504** [comment]
Is the issue fixed?

**Comment by N00Bmaster2810** [comment]
Can you please assign me this if it's finished  yet.

**Comment by Utkarsh1504** [comment]
no @ananya0504 not yet. you can start working on it.

**Comment by ananya0504** [comment]
Thanks @Utkarsh1504 
Will complete it asap

**Comment by DurveshKumarPal** [comment]
#37
